# config.yaml

DESA:
  BOT:
    TOKEN: 
      gAAAAABm6UHg7CNmQeYiDeBF0dAI3Jv-glO8BKnN7IXpg4kV9skPGHKp9cF6ACIOVr06S_s4sEAd8nHLkAvBe5Mx3SjxpuouyItNHtRLWLdtG0PDDrWZ0aPUQo8GlmNorKUQcbc2IA0B
  PATHS:
    SCRIPTS_PATH: .\scripts\
    RESOURCES_PATH: .\temp\
  AUTH:
    CREDENTIAL_VALIDITY_DAYS: 90
    VALIDATION_KEY: 
      gAAAAABm6UHgY2EDDnYGH0iEYxPGFlwlwbaWmpjFvhw1jEg1JaIY1HFM0kW4gxnAmoDxeui8RRmlsBBgW_g2wMAr0CmSBbULTA==
  LOGS:
    LOG_PATH: logs\bot.log
    LOG_LEVEL: DEBUG
  DATABASES:
    BOT_TELEGRAM:
      SERVER: .\
      SOURCE: 
        gAAAAABm6UHgLhq2L0VA1bRMdX7RjhyytvVspwrx7kxIXulgqUTjC2XDvkbzvRnTO_yWtsGToDe8mapP0WMRxsXLzzZcvus1JA==
  APIKEYS:
    ALPHA_VANTAGE: 
      gAAAAABm6UHgiLUhVvDEgVbgBxt1UiHHuF-6mlPn42_nxZaukZxF25g0i_-xzlpTlwTP7WiCa2KwyZLLxNpCDDjdJEc5gD3Z_H96dKhOPdHiYYbCEZUqM70=
    #Valido hasta: 2025-09-06 00:19:48
    BCRA: 
      gAAAAABm6UHg5GscnZIMfqUD1ZbRfBlxJeieJrGD77vo4eOt_cC_QhX-Ks09L3JdUGesqkivxSpBnH7w4ta-iO2F3OmsW_dz3V-TLs5Y_HY3pK8sJdC2hWLiIZx5XG2PX3pESx4o-jYXP6dilWwMlrkWmwRpJo64C6xX3SRF3JWUD5KcRq98DniFuuhHtW4hSajR6nkWrn1ZuLdQka9CfKQCSanLxeYlWlToyNPMMpCBI38fOzt3E3kT_xSBeOwQ0PX8BYCn9xWHPk1maRZNx9Q1dNJQT5CEtV1ILgF179rdDKAVwBbXQB6evhpVNA7NV5oYBlIhk4LZPVjyPIM3wjJEwUb4YI-zuC1T4DhLEyH73IqzgYlnai4=
  EMAIL:
    SMTP_SERVER: smtp.gmail.com
    SMTP_PORT: 587
    EMAIL_SENDER: 
      gAAAAABm6UHgf1E6B0-Wdght--0dxCnKmMcq7rk_TxDEUxrGZj58choZorXMINEW-4XGZKFfN-acyjNOX72HZL7889L8gon2T6s7B86VFktjqZGwRxPC4Gw=
    EMAIL_PASSWORD: 
      gAAAAABm6UHgZlGB6xOIxqTj0iqTvZddyooZVlGr8rcQO612CIqOjGEubqZiLJ7B2ODfP6aJ6vCPHfxO9HQxXjQd-p7b27iE6Q==
    INTERVAL_FOR_SEND: 1
  ALERTS:
    TEST_ACTIVATED: true
    WORKER_INTERVAL: 1800
    RECIPIENTS: 
      gAAAAABm6UHgExmAGgTa893tdmlIzWrJt8AgIHu3HrxoClXqCA7Y1CEsbL-7gKuKoZrCNWP0XxeIAQ8p4ZHvILu-jQTxwOI4JNapBqFVEj5w-GKSLdV_Jis=

TEST:
  BOT:
    TOKEN: 
      gAAAAABm6UHgblQzZ1FCEv9X0Y1YVt3RGp3jABLTBkwTIs2PqKdFFHXuxdwbYFAyq55h-6c6OA-d769ZlhcWv2QLVIFrA9h6Sfql1R7GHCi0RFLxarWZT_QNvwvUpkCHPK4LyxEZ3M5p
  PATHS:
    SCRIPTS_PATH: E:\Telegram_BOT\scripts\
    RESOURCES_PATH: E:\Telegram_BOT\temp\
  AUTH:
    CREDENTIAL_VALIDITY_DAYS: 90
    VALIDATION_KEY: 
      gAAAAABm6UHgqPB7Ofos4bBOR1fWnXr3wS0-K-kDAsylO-FJ0r9dH6W10xpMf6KRNblZgtBYkZjdTXBCOEKc_q_0y2MnC4rBZg==
  LOGS:
    LOG_PATH: E:\Telegram_BOT\logs\bot.log
    LOG_LEVEL: INFO
  DATABASES:
    BOT_TELEGRAM:
      SERVER: .\
      SOURCE: 
        gAAAAABm6UHg5evOJ3aM8ma4QVHK46nUc1AvmpSMlTKHSD_SHWzDB1GPOdhbJYN71im95rV3pHqnf2tlSUB5tFokoeeu5s3Mng==
  APIKEYS:
    ALPHA_VANTAGE: 
      gAAAAABm6UHgEy7suztK2rVv3X0K8RMPkIBr6--LCziKo2kgUStrXWuloAf28aiZQA0v_SurwAFSyvBTx0X_Y-NlBTznZERsoTCdboiYPf_Xz8rOuyXJvvQ=
    #Valido hasta: 2025-09-06 00:19:48
    BCRA: 
      gAAAAABm6UHgN48GqsxPSKMASFm6CGZJM2GFIlEVv05gerLc4OBwwVa-k8Kguk4Zu70ByIgA1XE1vjKIU-X4PoXM_G4P_ioqhmnN4s3EmAl3_77SDuw2EiYF1pdBaU-P-0QzUuTMqeyTYB67q6o3l05qfdLnNDlw7nHz1_RTOp0acFw0qOmHdQ4j_MNYaDGmD4tQNXnCpp7Q1W66yujIbh_nZLWBJDDGPZ2jzvPW03_LrmtaquVBXA0m8FH__HKNHBKEh66jVP5svYyV0rubmyqqBwyVu95A-Ttg-4lDiOOx8G-dtCslcNAwkyznEkiEjxLjtbG-Yd39iTxy86dtxqXwrrYzPCRi9UmsXT6mUbxi_ohKCXe5aBw=
  EMAIL:
    SMTP_SERVER: smtp.gmail.com
    SMTP_PORT: 587
    EMAIL_SENDER: 
      gAAAAABm6UHgTxDy10LtKFQ8i4nwfCpBCdzHtZzZ10it57YuS-PR0l5xcGomN47dFJGSlr9gHaeDLk3nS-TWedxRMNr4t5_h6XTm-sUPQ1iUIsNZmtGxf0U=
    EMAIL_PASSWORD: 
      gAAAAABm6UHgUZr-us8TvQf-xhp5L3wBG_KZFGC4e6eYDloCVQp_ju2cWdIOgjaaSrhQg3k4OQFG5R-hWz2pqf8HKthEJZq1fw1dC5jAVig7LJv7X2irUIU=
    INTERVAL_FOR_SEND: 1
  ALERTS:
    TEST_ACTIVATED: false
    WORKER_INTERVAL: 1800
    RECIPIENTS: 
      gAAAAABm6UHgcUPiYu3DvVlMYWy7GtwSaGVppJ0lk2t_d-M_7G-9KNix1X39z90ZHlBm4n0-4uJl-iB6A5Fg0prvS7Otbv8zg3V6JPD4VKnpvbxZ3FSstYY=

PROD:
  BOT:
    TOKEN: 
      gAAAAABm6UHg6_lML7XO6RUiNMQc0hNJ2721vxGU1ht3tScFvg28DNvLkQJ_eLnTTNxuDWZfSuQmmCItKGYLcE2LhhOBg4GS-NuKrLISH6ZsyJ2CykIgjdzoYarfTqIQOX2Kn8nIiPiL
  PATHS:
    SCRIPTS_PATH: E:\Telegram_BOT\scripts\
    RESOURCES_PATH: E:\Telegram_BOT\temp\
  AUTH:
    CREDENTIAL_VALIDITY_DAYS: 90
    VALIDATION_KEY: 
      gAAAAABm6UHgd9klLpHnU894K4-RPV_JiZnJ6a8e7n2BVaeF0s-UF9yScB-OKrbE-bSBKZsz6OY3eN8pK4FrQioyxOTvllG3gA==
  LOGS:
    LOG_PATH: E:\Telegram_BOT\logs\bot.log
    LOG_LEVEL: ERROR
  DATABASES:
    BOT_TELEGRAM:
      SERVER: .\
      SOURCE: 
        gAAAAABm6UHgoIzkravQ2sVwkepZKEIN-vdQIDzhnqyfUystErjGNUg5zsm8F-c8zDZrCr6lCavjQ0u6FnXuLtp39mBKwWfEWQ==
  APIKEYS:
    ALPHA_VANTAGE: 
      gAAAAABm6UHgKctNLwY68PngkPnrzadmUA-3JhJQe3niZCJ-l-Hpgp2ssUPMkIJN-TR31_F9GqUBrX5362Q8KgiPI11HZp7J-CESTtuelI2kxyp9FJHlzUk=
    #Valido hasta: 2025-09-06 00:19:48
    BCRA: 
      gAAAAABm6UHgCYbQJtk9hlC8QQ_5ODlfST28oITFvqFx-hEPCp61wfXEHKqf-DrIzZqXPXSeP70QwZzm8QOH_h1VaaIKxvCx2avIJDOhiISK1cfTUXYvGzM313lNmNoo9r05drEs2GFqIJqigxvkadvJtHWsmmR7zVgXyAFQnOHvdukbXlkt4yX2MrvQ752k2phVM5_cC-SFKOOFhQb1Hq5_VddPQZsODiOeDm_E1KTYvfbNC0yC-YX7AraqJh1I2XwHQdQlURYXQEvg9u_vB3QlZoiV7eO1g7a-fOEIRxCD5BJ4XbmlX-pz2qfkeMN5KZdvzvVBSMkOfOFSoISADBavb70zCcno2eeEMd6D0I4GAe-5VcA4ktA=
  EMAIL:
    SMTP_SERVER: smtp.gmail.com
    SMTP_PORT: 587
    EMAIL_SENDER: 
      gAAAAABm6UHgbRyDcp79miYP-tRNhpsD8UrSSEL5Edp5WAafJvXmEKIGpNqoJpQROINNlyoPVCg8G9eA5rtPDVqto-Vr2VnQYUmJesVn-DS4pUo94irK0Sw=
    EMAIL_PASSWORD: 
      gAAAAABm6UHgsPaukaBRglybN9iM8k6YgJWhVPqRSEW3npXLIr3yYHW_JnUJ4rkusB_n599RyitPpFMmxUnsPKr1e-h9-0Y2x54N5yU0MrM3VF7ATDrr_1s=
    INTERVAL_FOR_SEND: 1
  ALERTS:
    TEST_ACTIVATED: false
    WORKER_INTERVAL: 1800
    RECIPIENTS: 
      gAAAAABm6UHgJnLuZQAdW27dhxLDItxdwi8T6UL61GE7LTMVbXFT8mjp0ojuoW2TwC-tF2pTV5ZhzTJt5rP57F4FfNd5ehG0P4WJ9Lm_HAc2gmbla6afF84=
